In [23]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

Load the Data

In [24]:
data = pd.read_csv("regression.csv")
data.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

In [25]:
#create the regression 
x = data["SAT"]
y = data["GPA"]

In [26]:
x.shape

(84,)

In [27]:
y.shape

(84,)

In [28]:
x_matrix = x.values.reshape(-1, 1)
x_matrix.shape

(84, 1)

Regression itself

In [29]:
reg = LinearRegression()
reg.fit(x_matrix ,y)

LinearRegression()

R-squared

In [30]:
reg.score(x_matrix, y)

0.40600391479679754

In [31]:
#coefficient
reg.coef_

array([0.00165569])

In [32]:
#intercept
reg.intercept_

0.2750402996602799

Making predictions

In [41]:
reg.predict(x_matrix[[1,2]])

array([3.03010522, 3.18905127])

In [42]:
new_data = pd.DataFrame(data = [1740,1760],columns=['SAT'])
new_data

SAT
0  1740
1  1760

In [43]:
reg.predict(new_data)

array([3.15593751, 3.18905127])

In [44]:
new_data['Predicted_GPA'] = reg.predict(new_data)
new_data

SAT  Predicted_GPA
0  1740       3.155938
1  1760       3.189051