# Word Embedding Techniques using Ebmedding Layer in Keras

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
#sentences

In [3]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
##  Vocabulary size
voc_size = 100000

# One hot Representation

In [6]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[62065, 67411, 80808, 45513], [62065, 67411, 80808, 25901], [62065, 60536, 80808, 4849], [57383, 75049, 14784, 84803, 68582], [57383, 75049, 14784, 84803, 85094], [75082, 62065, 7560, 80808, 1280], [24737, 13806, 16559, 84803]]


# Word Embedding Representation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length = 8 
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[    0     0     0     0 62065 67411 80808 45513]
 [    0     0     0     0 62065 67411 80808 25901]
 [    0     0     0     0 62065 60536 80808  4849]
 [    0     0     0 57383 75049 14784 84803 68582]
 [    0     0     0 57383 75049 14784 84803 85094]
 [    0     0     0 75082 62065  7560 80808  1280]
 [    0     0     0     0 24737 13806 16559 84803]]


In [14]:
dim=10

In [15]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length = sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             1000000   
Total params: 1,000,000
Trainable params: 1,000,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(embedded_docs))

[[[-0.0343012   0.03184049 -0.04339122 -0.03576192 -0.02577572
    0.04483685 -0.02778286 -0.02252392 -0.02541499 -0.03778565]
  [-0.0343012   0.03184049 -0.04339122 -0.03576192 -0.02577572
    0.04483685 -0.02778286 -0.02252392 -0.02541499 -0.03778565]
  [-0.0343012   0.03184049 -0.04339122 -0.03576192 -0.02577572
    0.04483685 -0.02778286 -0.02252392 -0.02541499 -0.03778565]
  [-0.0343012   0.03184049 -0.04339122 -0.03576192 -0.02577572
    0.04483685 -0.02778286 -0.02252392 -0.02541499 -0.03778565]
  [-0.01685926  0.03738171 -0.00872846  0.03568861 -0.02219158
   -0.02394745 -0.02879537 -0.02797561 -0.01821692  0.03679622]
  [-0.04098509 -0.02360325  0.00592295 -0.00180838 -0.04429046
    0.0137358  -0.0171936  -0.00713013  0.04842496  0.02174861]
  [-0.02684375  0.04133615  0.03200281  0.02580987 -0.04503795
    0.04040953  0.02246957 -0.04669921 -0.00636894  0.02686081]
  [ 0.01370965 -0.00555806  0.04901413  0.03434998 -0.01328526
   -0.00562284 -0.01053036  0.04610033 -0.026951

In [18]:
embedded_docs[0]

array([    0,     0,     0,     0, 62065, 67411, 80808, 45513],
      dtype=int32)

In [19]:
print(model.predict(embedded_docs)[0])

[[-0.0343012   0.03184049 -0.04339122 -0.03576192 -0.02577572  0.04483685
  -0.02778286 -0.02252392 -0.02541499 -0.03778565]
 [-0.0343012   0.03184049 -0.04339122 -0.03576192 -0.02577572  0.04483685
  -0.02778286 -0.02252392 -0.02541499 -0.03778565]
 [-0.0343012   0.03184049 -0.04339122 -0.03576192 -0.02577572  0.04483685
  -0.02778286 -0.02252392 -0.02541499 -0.03778565]
 [-0.0343012   0.03184049 -0.04339122 -0.03576192 -0.02577572  0.04483685
  -0.02778286 -0.02252392 -0.02541499 -0.03778565]
 [-0.01685926  0.03738171 -0.00872846  0.03568861 -0.02219158 -0.02394745
  -0.02879537 -0.02797561 -0.01821692  0.03679622]
 [-0.04098509 -0.02360325  0.00592295 -0.00180838 -0.04429046  0.0137358
  -0.0171936  -0.00713013  0.04842496  0.02174861]
 [-0.02684375  0.04133615  0.03200281  0.02580987 -0.04503795  0.04040953
   0.02246957 -0.04669921 -0.00636894  0.02686081]
 [ 0.01370965 -0.00555806  0.04901413  0.03434998 -0.01328526 -0.00562284
  -0.01053036  0.04610033 -0.02695119 -0.0183474 ]]
